[
    {
        "doc": {
            "c0": "16-Dec-22",
            "ic": "ca09f-0ce2-4240-9e5b-958778618fea",
            "id": "dcf57ca5-27d6-421b-9605-365c3db3265a",
            "on": "CÔNG TY TNHH PANASONIC APPLIANCES VIỆT NAM",
            "ot": "0101382443",
            "ou": 1,
            "uc": "0101382443.api",
            "aun": 2,
            "idt": "2023-01-01 00:00",
            "org": {
                "on": "CÔNG TY TNHH PANASONIC APPLIANCES VIỆT NAM",
                "ot": "0101382443",
                "acc": "",
                "add": "Lô B-6, Khu công nghiệp Thăng Long, Xã Võng La, Huyện Đông Anh, Hà Nội, Xã Võng La, Huyện Đông Anh, Hà Nội",
                "seq": 2,
                "tel": "0914001408",
                "bank": "",
                "mail": "thuyht20@fpt.com.vn",
                "paxo": "10100",
                "sign": 2,
                "taxo": "10117",
                "paxoname": "Cục Thuế Thành Phố Hà Nội",
                "taxoname": "Chi cục Thuế huyện Đông Anh",
                "on_has_taxc": "CÔNG TY TNHH PANASONIC APPLIANCES VIỆT NAM",
                "tel_has_taxc": "0914001408",
                "addr_has_taxc": "Lô B-6, Khu công nghiệp Thăng Long, Xã Võng La, Huyện Đông Anh, Hà Nội, Xã Võng La, Huyện Đông Anh, Hà Nội",
                "degree_config": 123,
                "cfpitd_sign_coordinate": ""
            },
            "sec": "8gd4e2e8jg",
            "seq": "00000002",
            "sid": "ca09f-0ce2-4240-9e5b-958778618fea",
            "sum": 45678,
            "tax": [
                {
                    "amt": 45678,
                    "vat": 3654,
                    "vrn": "8%",
                    "vrt": "8",
                    "amtv": 45678,
                    "vatv": 3654
                }
            ],
            "vat": 3654,
            "bacc": "",
            "btax": "0313935315",
            "btel": "",
            "curr": "VND",
            "exrt": 1,
            "form": "1",
            "name": "HÓA ĐƠN GIÁ TRỊ GIA TĂNG",
            "note": "AR INVOICE",
            "paym": "TM/CK",
            "sacc": "",
            "sign": 1,
            "stax": "0101382443",
            "stel": "0914001408",
            "sumv": 45678,
            "taxo": "10117",
            "type": "01GTKT",
            "vatv": 3654,
            "word": "Bốn mươi chín nghìn ba trăm ba mươi hai dong",
            "baddr": "1 HA LONG BAY, HOI AN, 12, Viet Nam",
            "bbank": "",
            "bcode": "BENTESSGN",
            "bmail": "",
            "bname": "BEN'S TEST REGISTRATION",
            "buyer": "",
            "items": [
                {
                    "c0": "3654.00",
                    "c1": "49332.00",
                    "c2": "45678.00",
                    "c3": "",
                    "id": "_bjope1ipu",
                    "vat": 3654,
                    "vrn": "8%",
                    "vrt": "8",
                    "line": 1,
                    "name": "Administration",
                    "type": "",
                    "unit": "Unit",
                    "price": 45678,
                    "total": 49332,
                    "amount": 45678,
                    "quantity": 1
                }
            ],
            "saddr": "Lô B-6, Khu công nghiệp Thăng Long, Xã Võng La, Huyện Đông Anh, Hà Nội, Xã Võng La, Huyện Đông Anh, Hà Nội",
            "sbank": "",
            "smail": "thuyht20@fpt.com.vn",
            "sname": "CÔNG TY TNHH PANASONIC APPLIANCES VIỆT NAM",
            "total": 49332,
            "serial": "C23TCE",
            "status": 2,
            "totalv": 49332,
            "hascode": 1,
            "discount": "",
            "sendfile": 1,
            "sendtype": 1,
            "type_ref": 1,
            "tradeamount": 0,
            "tradeamountv": 0
        }
    }
]